Add Lab 3 problem and solution from class F
laymonage/TarungLab pull request #5
Opened 2017-10-25 15:57 UTC by giovanism

Lab03_F.md: Instructions and hints
Lab03_F.py: Solution

2017-10-25 23:56 UTC, laymonage commented on Lab/03/Lab03_F.py
> +dec = int(input("Give a possitive integer in decimal representation: "))
possitive -> positive

2017-10-25 23:57 UTC, laymonage requested changes

2017-10-25 23:57 UTC, laymonage commented on Lab/03/Lab03_F.py
> +dec = int(input("Give a possitive integer in decimal representation: "))
possitive -> positive

2017-10-25 23:57 UTC, laymonage commented on Lab/03/Lab03_F.py
> +    "Give a possitive integer in hexadecimal representation: "
Same as above.

2017-10-26 00:47 UTC, giovanism commented
Updated

2017-10-26 01:10 UTC, merged